ci:
  autoupdate_schedule: "quarterly"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ".*(src.tex.*|notebooks.*)$"
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ".*(src.tex.*|notebooks.*)$"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.7"
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        additional_dependencies: [toml]
      - id: black-jupyter
        additional_dependencies: [toml]
