channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip=23.1
  - cython

  - asdf
  - asdf-astropy
  - astroquery>0.4
  - astropy=5.2
  - dustmaps=1.0
  - healpy=1.16
  - matplotlib=3.7
  - numpy=1.24
  - scipy=1.11
  - shapely
  - tqdm=4.65

  - pip:
      - daft
      - gaiadr3-zeropoint>=0.0.4
      - gala>=1.6,<1.7
      - galstreams>1.0
      - nflows
      - pre-commit
      - pyia==1.3
      - showyourwork
      - zuko==0.3.1
      - git+https://github.com/joshspeagle/brutus.git
      - git+https://github.com/GalOrrery/stream_ml-pytorch.git
      - git+https://github.com/GalOrrery/stream_ml-visualization.git
